name: CI/CD
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Copy ENV file
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Create DB and schemas
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Launch tests
        run: php artisan test
  deploy:
    if: github.ref == 'refs/heads/master'
      needs: [tests]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Deploy
          env:
            DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          run: |
            eval "$(ssh-agent -s)"
            ssh-add - <<< "${DEPLOY_KEY}"
            mkdir ~/.ssh
            echo -e "HostName shineboard.io\n\tStrictHostKeyChecking no\n\t"User deploy >> ~/.ssh/config
            composer install
            vendor/bin/dep deploy
